name: Uploader
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Upload binaries to release
        if: matrix.goos == 'windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: F:\actions-runner\_work\connectix_microsoft_store_archives\connectix_microsoft_store_archives\Connectix_installer.exe
          tag: ${{ github.ref }}
          file_glob: true
          
